# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage
default_platform(:ios)
setup_ci if ENV['CI']

platform :ios do
  desc "Build development version"
  lane :dev do
    import_certificate(
      certificate_path: "#{ENV['RUNNER_TEMP']}/cert.p12",
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"]
    )
    # 2 provisioning profiles, 1 for the main app and 1 for the share extension
    install_provisioning_profile(path: "#{ENV['RUNNER_TEMP']}/buildpp.mobileprovision")
    install_provisioning_profile(path: "#{ENV['RUNNER_TEMP']}/shareextpp.mobileprovision")
    gym(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      codesigning_identity: "Apple Development: Nguyen Thai",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "com.linagora.ios.linshare" => "linshare.development.profile",
          "com.linagora.ios.linshare.extension" => "linshare.share.ext.development.profile"
        }
      }
    )
  end
end
