# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage
default_platform(:ios)

platform :ios do
  desc "Build development version"
  lane :dev do
    create_keychain(
      name: "linshare",
      default_keychain: true,
      password: ENV["KEYCHAIN_PASSWORD"]
      unlock: true,
      timeout: 3600,
    )
    import_certificate(
      certificate_path: "cert.p12",
      certificate_password: ENV["CERTIFICATE_PASSWORD"],
      keychain_password: ENV["KEYCHAIN_PASSWORD"]
    )
    sh 'mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles'
    sh 'cp *.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles'
    gym(
      scheme: "Runner",
      workspace: "Runner.xcworkspace",
      codesigning_identity: "Apple Development: Nguyen Thai",
      export_method: "development",
      export_options: {
        provisioningProfiles: {
          "com.linagora.ios.linshare" => "linshare.development.profile",
          "com.linagora.ios.linshare.extension" => "linshare.share.ext.development.profile"
        }
      }
    )
  end
end
