on:
  workflow_dispatch:

name: Build dev versions

jobs:
  analyze-test:
    uses: ./.github/workflows/analyze-test.yaml

  build-android:
    name: Build Android apps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
          cache-key: deps-${{ hashFiles('pubspec.lock') }} # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter # optional, change this to specify the cache path
      - name: Setup environment
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$GOOGLE_SERVICES_JSON" > app/google-services.json
        working-directory: android

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "ruby"
          bundler-cache: true
          working-directory: android

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Run prebuild
        run: bash prebuild.sh

      - name: Build APK
        env:
          CAPTCHA_TOKEN: ${{ secrets.CAPTCHA_TOKEN }}
          SAAS_AVAILABLE: "true"
        run: bundle exec fastlane dev
        working-directory: android

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: linshare-dev
          path: "build/app/outputs/flutter-apk/app-release.apk"
